# Generated by Django 6.0.6 on 2026-06-17 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('ikigai', 'Paso 1: ¿Quién eres y qué te mueve? (Ikigai)'), ('field_diary', 'Paso 2: Abre los ojos (Diario de Campo)'), ('empathy', 'Paso 3: Enamórate del problema (Mapa de Empatía + POV)'), ('jtbd', 'Paso 4: ¿Qué trabajo está contratando tu cliente? (JTBD)'), ('ideation', 'Paso 5: Genera ideas (Brainstorming + SCAMPER)'), ('value_prop', 'Paso 6: Construye tu propuesta de valor (Value Proposition Canvas)'), ('validation', 'Paso 7: Valida con personas reales (Entrevistas)')], max_length=50, unique=True, verbose_name='Identificador del módulo')),
                ('order', models.IntegerField(help_text='Orden secuencial del módulo (1-7)', unique=True, verbose_name='Orden')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(help_text='Descripción del propósito del módulo', verbose_name='Descripción')),
                ('instructions', models.TextField(help_text='Instrucciones paso a paso para completar el módulo', verbose_name='Instrucciones')),
                ('estimated_time_minutes', models.IntegerField(help_text='Tiempo aproximado para completar el módulo', verbose_name='Tiempo estimado (minutos)')),
                ('is_active', models.BooleanField(default=True, help_text='Si está desactivado, no aparecerá en el recorrido', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('required_fields', 'Campos requeridos'), ('min_count', 'Cantidad mínima'), ('custom_logic', 'Lógica personalizada')], max_length=50, verbose_name='Tipo de regla')),
                ('field_name', models.CharField(blank=True, help_text='Para reglas de campos o conteo', max_length=100, verbose_name='Nombre del campo')),
                ('min_value', models.IntegerField(blank=True, help_text='Para reglas de conteo mínimo', null=True, verbose_name='Valor mínimo')),
                ('error_message', models.TextField(help_text='Mensaje a mostrar si no se cumple la regla', verbose_name='Mensaje de error')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Regla de Validación',
                'verbose_name_plural': 'Reglas de Validación',
                'ordering': ['module__order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título del ejemplo')),
                ('territory_context', models.CharField(help_text='Ej: Municipio de Ituango, Antioquia (PDET)', max_length=255, verbose_name='Contexto territorial')),
                ('description', models.TextField(help_text='Narrativa del ejemplo aplicado al territorio', verbose_name='Descripción')),
                ('key_learnings', models.TextField(blank=True, help_text='Lecciones que ilustra este ejemplo', verbose_name='Aprendizajes clave')),
                ('is_featured', models.BooleanField(default=False, help_text='Mostrar como ejemplo principal', verbose_name='Destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='core.module', verbose_name='Módulo')),
            ],
            options={
                'verbose_name': 'Ejemplo',
                'verbose_name_plural': 'Ejemplos',
                'ordering': ['module__order', '-is_featured', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'No iniciado'), ('in_progress', 'En progreso'), ('completed', 'Completado'), ('blocked', 'Bloqueado')], default='not_started', max_length=20, verbose_name='Estado')),
                ('completion_percentage', models.IntegerField(default=0, help_text='0-100', verbose_name='Porcentaje de completitud')),
                ('validation_passed', models.BooleanField(default=False, help_text='Si cumple todos los criterios de validación', verbose_name='Validación pasada')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de completitud')),
                ('facilitator_notes', models.TextField(blank=True, verbose_name='Notas del facilitador')),
                ('facilitator_override', models.BooleanField(default=False, help_text='Si el facilitador marcó manualmente como completado', verbose_name='Override del facilitador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='core.module', verbose_name='Módulo')),
            ],
            options={
                'verbose_name': 'Progreso de Módulo',
                'verbose_name_plural': 'Progresos de Módulos',
                'ordering': ['module__order'],
            },
        ),
    ]
