# Generated by Django 6.0.6 on 2026-06-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='common_errors',
            field=models.TextField(blank=True, help_text='Lista de errores frecuentes que evitar', verbose_name='Errores comunes'),
        ),
        migrations.AddField(
            model_name='module',
            name='deliverable_description',
            field=models.TextField(blank=True, help_text='Qué debe registrar el emprendedor en la plataforma', verbose_name='Descripción del entregable'),
        ),
        migrations.AddField(
            model_name='module',
            name='how_to_guide',
            field=models.TextField(blank=True, help_text='Instrucciones detalladas con ejemplos orientadores', verbose_name='Cómo hacerlo - Guía paso a paso'),
        ),
        migrations.AddField(
            model_name='module',
            name='why_exists',
            field=models.TextField(blank=True, help_text='Fundamento teórico y justificación del módulo', verbose_name='Por qué existe este paso'),
        ),
        migrations.AlterField(
            model_name='module',
            name='instructions',
            field=models.TextField(blank=True, help_text='Instrucciones paso a paso para completar el módulo', verbose_name='Instrucciones'),
        ),
    ]
