# Generated by Django 6.0.6 on 2026-06-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_module_common_errors_module_deliverable_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Ej: jtbd, pov, pdet, empathy_map', max_length=100, unique=True, verbose_name='Identificador único')),
                ('category', models.CharField(choices=[('methodology', 'Metodología'), ('territorial', 'Contexto Territorial'), ('platform', 'Plataforma')], max_length=50, verbose_name='Categoría')),
                ('title', models.CharField(help_text='Ej: Jobs To Be Done, PDET, Mapa de Empatía', max_length=255, verbose_name='Título')),
                ('short_definition', models.TextField(help_text='2-3 líneas. Aparece en modal y búsqueda.', verbose_name='Definición corta')),
                ('detailed_explanation', models.TextField(help_text='Markdown con ejemplos. Aparece en página completa glosario.', verbose_name='Explicación detallada')),
                ('external_links', models.JSONField(blank=True, default=list, help_text='Lista de dicts: [{"title": "...", "url": "...", "type": "video|article|tool"}]', verbose_name='Links externos')),
                ('keywords', models.JSONField(blank=True, default=list, help_text='Lista para búsqueda: ["emprendimiento", "rural", "validación"]', verbose_name='Palabras clave')),
                ('order', models.IntegerField(default=0, help_text='Para ordenamiento en glosario', verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('related_modules', models.ManyToManyField(blank=True, related_name='reference_contents', to='core.module', verbose_name='Módulos relacionados')),
            ],
            options={
                'verbose_name': 'Contenido de Referencia',
                'verbose_name_plural': 'Contenidos de Referencia',
                'ordering': ['category', 'order', 'title'],
            },
        ),
    ]
