# Generated by Django 6.0.6 on 2026-06-21 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_referencecontent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='Empresa')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cliente/Inversor',
                'verbose_name_plural': 'Clientes/Inversores',
            },
        ),
        migrations.CreateModel(
            name='Venture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del emprendimiento')),
                ('status', models.CharField(choices=[('diagnostic', 'En Diagnóstico'), ('active', 'Activo'), ('paused', 'Pausado'), ('completed', 'Completado')], default='diagnostic', max_length=50, verbose_name='Estado')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('total_investment', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Inversión total')),
                ('hours_logged', models.IntegerField(default=0, verbose_name='Horas registradas')),
                ('territory', models.CharField(blank=True, max_length=255, verbose_name='Territorio/Municipio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_ventures', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Emprendimiento',
                'verbose_name_plural': 'Emprendimientos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inversión')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client', verbose_name='Cliente/Inversor')),
                ('venture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venture', verbose_name='Emprendimiento')),
            ],
            options={
                'verbose_name': 'Inversión',
                'verbose_name_plural': 'Inversiones',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Ally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=255, verbose_name='Organización')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('ventures', models.ManyToManyField(blank=True, related_name='allies', to='core.venture', verbose_name='Emprendimientos')),
            ],
            options={
                'verbose_name': 'Aliado',
                'verbose_name_plural': 'Aliados',
            },
        ),
        migrations.CreateModel(
            name='VentureEntrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('lead', 'Líder'), ('member', 'Miembro')], default='member', max_length=50, verbose_name='Rol')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de incorporación')),
                ('entrepreneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Emprendedor')),
                ('venture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venture', verbose_name='Emprendimiento')),
            ],
            options={
                'verbose_name': 'Emprendedor en Emprendimiento',
                'verbose_name_plural': 'Emprendedores en Emprendimientos',
                'unique_together': {('venture', 'entrepreneur')},
            },
        ),
        migrations.AddField(
            model_name='venture',
            name='entrepreneurs',
            field=models.ManyToManyField(related_name='ventures', through='core.VentureEntrepreneur', to=settings.AUTH_USER_MODEL, verbose_name='Emprendedores'),
        ),
    ]
