# Generated by Django 6.0.6 on 2026-06-17 05:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('entrepreneur', 'Emprendedor'), ('facilitator', 'Facilitador'), ('admin', 'Administrador')], default='entrepreneur', max_length=20, verbose_name='Tipo de usuario')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número de teléfono')),
                ('profile_complete', models.BooleanField(default=False, verbose_name='Perfil completo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EntrepreneurProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('identification_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de identificación')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(blank=True, max_length=50, verbose_name='Género')),
                ('education_level', models.CharField(blank=True, choices=[('none', 'Sin educación formal'), ('primary', 'Primaria'), ('secondary', 'Bachillerato'), ('technical', 'Técnico/Tecnológico'), ('university', 'Universitario'), ('postgraduate', 'Posgrado')], max_length=20, verbose_name='Nivel educativo')),
                ('territory_type', models.CharField(choices=[('rural', 'Rural'), ('urban_peripheral', 'Urbano periférico'), ('urban_central', 'Urbano central'), ('pdet', 'Territorio PDET')], max_length=20, verbose_name='Tipo de territorio')),
                ('department', models.CharField(max_length=100, verbose_name='Departamento')),
                ('municipality', models.CharField(max_length=100, verbose_name='Municipio')),
                ('village_or_neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Vereda/Barrio')),
                ('is_displaced', models.BooleanField(default=False, verbose_name='Víctima de desplazamiento')),
                ('is_conflict_victim', models.BooleanField(default=False, verbose_name='Víctima del conflicto')),
                ('is_ethnic_minority', models.BooleanField(default=False, verbose_name='Minoría étnica')),
                ('previous_entrepreneurship_experience', models.BooleanField(default=False, verbose_name='Experiencia previa en emprendimiento')),
                ('bio', models.TextField(blank=True, verbose_name='Biografía')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('assigned_facilitator', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'facilitator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_entrepreneurs', to=settings.AUTH_USER_MODEL, verbose_name='Facilitador asignado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrepreneur_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Emprendedor',
                'verbose_name_plural': 'Perfiles de Emprendedores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacilitatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('organization', models.CharField(blank=True, max_length=255, verbose_name='Organización')),
                ('departments_covered', models.JSONField(default=list, help_text='Lista de departamentos donde trabaja', verbose_name='Departamentos que cubre')),
                ('municipalities_covered', models.JSONField(default=list, help_text='Lista de municipios donde trabaja', verbose_name='Municipios que cubre')),
                ('specialization', models.TextField(blank=True, help_text='Áreas de expertise o sectores específicos', verbose_name='Especialización')),
                ('max_entrepreneurs', models.IntegerField(default=20, help_text='Número máximo de emprendedores que puede acompañar simultáneamente', verbose_name='Máximo de emprendedores')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facilitator_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Facilitador',
                'verbose_name_plural': 'Perfiles de Facilitadores',
                'ordering': ['-created_at'],
            },
        ),
    ]
