# Generated by Django 6.0.6 on 2026-06-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('entrepreneur', 'Emprendedor'), ('facilitator', 'Facilitador'), ('admin', 'Administrador'), ('ally', 'Aliado'), ('client', 'Cliente/Inversor')], default='entrepreneur', max_length=20, verbose_name='Tipo de usuario'),
        ),
    ]
