# Generated by Django 6.0.6 on 2026-06-17 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1, verbose_name='Versión')),
                ('is_current', models.BooleanField(default=True, help_text='Solo la versión más reciente debe ser True', verbose_name='Versión actual')),
                ('is_validated', models.BooleanField(default=False, help_text='Si cumple criterios de validación', verbose_name='Validado')),
                ('validation_errors', models.JSONField(blank=True, default=dict, help_text='Diccionario con errores por campo', verbose_name='Errores de validación')),
                ('facilitator_comment', models.TextField(blank=True, verbose_name='Comentario del facilitador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='core.module', verbose_name='Módulo')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Entregable',
                'verbose_name_plural': 'Entregables',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageDeliverable',
            fields=[
                ('deliverable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='deliverables.deliverable')),
                ('image_file', models.ImageField(upload_to='deliverables/images/%Y/%m/%d/', verbose_name='Archivo de imagen')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='deliverables/thumbnails/%Y/%m/%d/', verbose_name='Miniatura')),
                ('caption', models.TextField(blank=True, help_text='Descripción opcional de la imagen', verbose_name='Descripción')),
                ('field_reference', models.CharField(blank=True, help_text='Nombre del campo que documenta (ej: observation_3)', max_length=100, verbose_name='Campo asociado')),
            ],
            options={
                'verbose_name': 'Entregable de Imagen',
                'verbose_name_plural': 'Entregables de Imagen',
            },
            bases=('deliverables.deliverable',),
        ),
        migrations.CreateModel(
            name='TextDeliverable',
            fields=[
                ('deliverable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='deliverables.deliverable')),
                ('data', models.JSONField(help_text='Datos estructurados del formulario', verbose_name='Datos')),
                ('summary', models.TextField(blank=True, help_text='Resumen en texto plano para búsqueda', verbose_name='Resumen')),
            ],
            options={
                'verbose_name': 'Entregable de Texto',
                'verbose_name_plural': 'Entregables de Texto',
            },
            bases=('deliverables.deliverable',),
        ),
        migrations.CreateModel(
            name='VoiceDeliverable',
            fields=[
                ('deliverable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='deliverables.deliverable')),
                ('audio_file', models.FileField(upload_to='deliverables/audio/%Y/%m/%d/', verbose_name='Archivo de audio')),
                ('duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='Duración (segundos)')),
                ('transcription', models.TextField(blank=True, help_text='Transcripción automática o manual del audio', verbose_name='Transcripción')),
                ('transcription_status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completada'), ('failed', 'Fallida'), ('not_needed', 'No necesaria')], default='pending', max_length=20, verbose_name='Estado de transcripción')),
                ('field_reference', models.CharField(blank=True, help_text='Nombre del campo del formulario que responde', max_length=100, verbose_name='Campo asociado')),
            ],
            options={
                'verbose_name': 'Entregable de Audio',
                'verbose_name_plural': 'Entregables de Audio',
            },
            bases=('deliverables.deliverable',),
        ),
    ]
