# Generated by Django 6.0.6 on 2026-06-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='overall_quality',
            field=models.IntegerField(default=0, help_text='Score 0-100 basado en validadores', verbose_name='Calidad general'),
        ),
    ]
